### ISSUE TITLE
Promise中resolve一个Promise执行时机错误

### ISSUE THREAD

**Issue by zhaoyuqiqi** [coderwhy/HYPromise#2]
如果这个promise1的resolve中，resolve一个promise2，应该是等待其中的promise2状态变更后再执行当前promise1的then方法，现在HYPromise跟Promise的表现不一致，例如：
```ts
const p = new HYPromise((resolve) => {
  setTimeout(() => {
    resolve();
  }, 1000);
});
const p1 = new HYPromise((resolve) => {
  resolve(p);
});
p1.then(()=> {
  // 这个位置应该等待1秒后执行，但是现在是立即执行了
});
```
[fix: 修复在构造函数中resolve一个Promise或类Promise时返回错误 #3](https://github.com/coderwhy/HYPromise/pull/3)

**Comment by sciencefunq** [comment]
你是对的。

**Comment by coderwhy** [comment]
这个代码旨在实现Promises/A+规范，Promises/A+规范一些表现和目前的Promise有差异。
你修复的代码不能完全通过Promises/A+规范，后续我们再更新一些ES6的Promise功能。
