### ISSUE TITLE
HYPromise.reject()无法直接抛出错误

### ISSUE THREAD

**Issue by zhaoyuqiqi** [coderwhy/HYPromise#4]
```ts
HYPromise.reject(2)
```
无法直接抛出错误，即使未处理这个也不会报错

**Comment by coderwhy** [comment]
用catch可以正常捕获到错误信息的，目前是实现 Promises/A+ specifications，并没有刻意去让一些功能和目前的Promise完全一致。
后续有时间会继续更新的。
